const dayjs = require('dayjs');

const plaidRecurringTransactions = {
  updated_datetime: dayjs().toISOString(),
  inflow_streams: [],
  outflow_streams: [
    {
      account_id: 'pld-1MB8K38rdPHmrrdaOZKBU7xy95qZB1sn878Om',
      stream_id: 'stream-outflow-prime',
      category: ['Digital Services', 'Streaming'],
      category_id: '22016000',
      description: 'Amazon Prime Student',
      merchant_name: 'Amazon',
      personal_finance_category: {
        primary: 'ENTERTAINMENT',
        detailed: 'ENTERTAINMENT_TV_AND_MOVIES',
        confidence_level: 'HIGH',
      },
      first_date: '2025-03-17',
      last_date: '2025-03-17',
      predicted_next_date: '2025-04-17',
      frequency: 'MONTHLY',
      transaction_ids: ['txn-prime-001', 'txn-prime-002'],
      average_amount: { amount: 7.49, iso_currency_code: 'USD' },
      last_amount: { amount: 7.49, iso_currency_code: 'USD' },
      is_active: true,
      status: 'MATURE',
      is_user_modified: false,
    },
    {
      account_id: 'pld-1MB8K38rdPHmrrdaOZKBU7xy95qZB1sn878Om',
      stream_id: 'stream-outflow-planet',
      category: ['Health and Fitness', 'Gyms and Fitness Centers'],
      category_id: '22010000',
      description: 'Planet Fitness Classic Membership',
      merchant_name: 'Planet Fitness',
      personal_finance_category: {
        primary: 'HEALTH_AND_FITNESS',
        detailed: 'HEALTH_AND_FITNESS_GYM',
        confidence_level: 'HIGH',
      },
      first_date: '2025-03-11',
      last_date: '2025-03-11',
      predicted_next_date: '2025-04-11',
      frequency: 'MONTHLY',
      transaction_ids: ['txn-planet-001', 'txn-planet-002'],
      average_amount: { amount: 15.0, iso_currency_code: 'USD' },
      last_amount: { amount: 15.0, iso_currency_code: 'USD' },
      is_active: true,
      status: 'MATURE',
      is_user_modified: false,
    },
    {
      account_id: 'pld-1MB8K38rdPHmrrdaOZKBU7xy95qZB1sn878Om',
      stream_id: 'stream-outflow-netflix',
      category: ['Digital Services', 'Streaming'],
      category_id: '22016000',
      description: 'Netflix Subscription',
      merchant_name: 'Netflix',
      personal_finance_category: {
        primary: 'ENTERTAINMENT',
        detailed: 'ENTERTAINMENT_TV_AND_MOVIES',
        confidence_level: 'HIGH',
      },
      first_date: '2025-03-23',
      last_date: '2025-03-23',
      predicted_next_date: '2025-04-23',
      frequency: 'MONTHLY',
      transaction_ids: ['txn-netflix-001', 'txn-netflix-002'],
      average_amount: { amount: 17.99, iso_currency_code: 'USD' },
      last_amount: { amount: 17.99, iso_currency_code: 'USD' },
      is_active: true,
      status: 'MATURE',
      is_user_modified: true,
      last_user_modified_datetime: '2025-05-03T12:00:00Z',
    },
    {
      account_id: 'pld-1MB8K38rdPHmrrdaOZKBU7xy95qZB1sn878Om',
      stream_id: 'stream-outflow-prime',
      category: ['Digital Services', 'Streaming'],
      category_id: '22016000',
      description: 'Amazon Prime Student',
      merchant_name: 'Amazon',
      personal_finance_category: {
        primary: 'ENTERTAINMENT',
        detailed: 'ENTERTAINMENT_TV_AND_MOVIES',
        confidence_level: 'HIGH',
      },
      first_date: '2025-04-17',
      last_date: '2025-04-17',
      predicted_next_date: '2025-05-17',
      frequency: 'MONTHLY',
      transaction_ids: ['txn-prime-003', 'txn-prime-004'],
      average_amount: { amount: 7.49, iso_currency_code: 'USD' },
      last_amount: { amount: 7.49, iso_currency_code: 'USD' },
      is_active: true,
      status: 'MATURE',
      is_user_modified: false,
    },
    {
      account_id: 'pld-1MB8K38rdPHmrrdaOZKBU7xy95qZB1sn878Om',
      stream_id: 'stream-outflow-planet',
      category: ['Health and Fitness', 'Gyms and Fitness Centers'],
      category_id: '22010000',
      description: 'Planet Fitness Classic Membership',
      merchant_name: 'Planet Fitness',
      personal_finance_category: {
        primary: 'HEALTH_AND_FITNESS',
        detailed: 'HEALTH_AND_FITNESS_GYM',
        confidence_level: 'HIGH',
      },
      first_date: '2025-04-11',
      last_date: '2025-04-11',
      predicted_next_date: '2025-05-11',
      frequency: 'MONTHLY',
      transaction_ids: ['txn-planet-003', 'txn-planet-004'],
      average_amount: { amount: 15.0, iso_currency_code: 'USD' },
      last_amount: { amount: 15.0, iso_currency_code: 'USD' },
      is_active: true,
      status: 'MATURE',
      is_user_modified: false,
    },
    {
      account_id: 'pld-1MB8K38rdPHmrrdaOZKBU7xy95qZB1sn878Om',
      stream_id: 'stream-outflow-netflix',
      category: ['Digital Services', 'Streaming'],
      category_id: '22016000',
      description: 'Netflix Subscription',
      merchant_name: 'Netflix',
      personal_finance_category: {
        primary: 'ENTERTAINMENT',
        detailed: 'ENTERTAINMENT_TV_AND_MOVIES',
        confidence_level: 'HIGH',
      },
      first_date: '2025-04-23',
      last_date: '2025-04-23',
      predicted_next_date: '2025-05-23',
      frequency: 'MONTHLY',
      transaction_ids: ['txn-netflix-003', 'txn-netflix-004'],
      average_amount: { amount: 17.99, iso_currency_code: 'USD' },
      last_amount: { amount: 17.99, iso_currency_code: 'USD' },
      is_active: true,
      status: 'MATURE',
      is_user_modified: true,
      last_user_modified_datetime: '2025-04-20T12:00:00Z',
    },
    {
      account_id: 'pld-1MB8K38rdPHmrrdaOZKBU7xy95qZB1sn878Om',
      stream_id: 'stream-outflow-prime',
      category: ['Digital Services', 'Streaming'],
      category_id: '22016000',
      description: 'Amazon Prime Student',
      merchant_name: 'Amazon',
      personal_finance_category: {
        primary: 'ENTERTAINMENT',
        detailed: 'ENTERTAINMENT_TV_AND_MOVIES',
        confidence_level: 'HIGH',
      },
      first_date: '2025-05-17',
      last_date: '2025-05-17',
      predicted_next_date: '2025-06-17',
      frequency: 'MONTHLY',
      transaction_ids: ['txn-prime-005', 'txn-prime-006'],
      average_amount: { amount: 7.49, iso_currency_code: 'USD' },
      last_amount: { amount: 7.49, iso_currency_code: 'USD' },
      is_active: true,
      status: 'MATURE',
      is_user_modified: false,
    },
    {
      account_id: 'pld-1MB8K38rdPHmrrdaOZKBU7xy95qZB1sn878Om',
      stream_id: 'stream-outflow-planet',
      category: ['Health and Fitness', 'Gyms and Fitness Centers'],
      category_id: '22010000',
      description: 'Planet Fitness Classic Membership',
      merchant_name: 'Planet Fitness',
      personal_finance_category: {
        primary: 'HEALTH_AND_FITNESS',
        detailed: 'HEALTH_AND_FITNESS_GYM',
        confidence_level: 'HIGH',
      },
      first_date: '2025-05-11',
      last_date: '2025-05-11',
      predicted_next_date: '2025-06-11',
      frequency: 'MONTHLY',
      transaction_ids: ['txn-planet-005', 'txn-planet-006'],
      average_amount: { amount: 15.0, iso_currency_code: 'USD' },
      last_amount: { amount: 15.0, iso_currency_code: 'USD' },
      is_active: true,
      status: 'MATURE',
      is_user_modified: false,
    },
    {
      account_id: 'pld-1MB8K38rdPHmrrdaOZKBU7xy95qZB1sn878Om',
      stream_id: 'stream-outflow-netflix',
      category: ['Digital Services', 'Streaming'],
      category_id: '22016000',
      description: 'Netflix Subscription',
      merchant_name: 'Netflix',
      personal_finance_category: {
        primary: 'ENTERTAINMENT',
        detailed: 'ENTERTAINMENT_TV_AND_MOVIES',
        confidence_level: 'HIGH',
      },
      first_date: '2025-05-23',
      last_date: '2025-05-23',
      predicted_next_date: '2025-06-23',
      frequency: 'MONTHLY',
      transaction_ids: ['txn-netflix-005', 'txn-netflix-006'],
      average_amount: { amount: 17.99, iso_currency_code: 'USD' },
      last_amount: { amount: 17.99, iso_currency_code: 'USD' },
      is_active: true,
      status: 'MATURE',
      is_user_modified: true,
      last_user_modified_datetime: '2025-05-10T12:00:00Z',
    },
  ],
  request_id: 'plaid-request-id-yRGB9Pra9cE6w4v8Q4427NnFXRaRoySM',
};

module.exports = plaidRecurringTransactions;
